export const LIST_TAB = [
  {
    id: 1,
    name: 'Danh sách Hồ sơ gửi đi',
    numberShow: 0,
    parentId: 0,
    isVisitTab: true,
    isFocusTab: true,
    sortId: 0,
    listRoles: [
      {
        roleValue: 1,
        roleName: 'Truy cập trang',
        roleIDName: 'FROM_LIST',
        tabID: 1,
        isRole: false,
        tabName: 'Danh sách Hồ sơ gửi đi',
        sortId: 0,
      },
      {
        roleValue: 2,
        roleName: 'Xem tất cả Hồ sơ của Đơn vị',
        roleIDName: 'FROM_ALL',
        tabID: 1,
        isRole: false,
        tabName: 'Danh sách Hồ sơ gửi đi',
        sortId: 0,
      },
      {
        roleValue: 4,
        roleName: 'Tạo Hồ sơ',
        roleIDName: 'FROM_CREATE',
        tabID: 1,
        isRole: false,
        tabName: 'Danh sách Hồ sơ gửi đi',
        sortId: 0,
      },
      {
        roleValue: 2048,
        roleName: 'Tạo Hồ sơ tự động ký',
        roleIDName: 'FROM_CREATE_AUTO_SIGN',
        tabID: 1,
        isRole: false,
        tabName: 'Danh sách Hồ sơ gửi đi',
        sortId: 0,
      },
      {
        roleValue: 8,
        roleName: 'Xem chi tiết Hồ sơ',
        roleIDName: 'FROM_VIEWDETAIL',
        tabID: 1,
        isRole: false,
        tabName: 'Danh sách Hồ sơ gửi đi',
        sortId: 0,
      },
      {
        roleValue: 16,
        roleName: 'Ký Hồ sơ',
        roleIDName: 'FROM_APPROVE',
        tabID: 1,
        isRole: false,
        tabName: 'Danh sách Hồ sơ gửi đi',
        sortId: 0,
      },
      {
        roleValue: 32,
        roleName: 'Xóa Hồ sơ',
        roleIDName: 'FROM_CANCEL',
        tabID: 1,
        isRole: false,
        tabName: 'Danh sách Hồ sơ gửi đi',
        sortId: 0,
      },
      {
        roleValue: 64,
        roleName: 'Khôi phục Hồ sơ',
        roleIDName: 'FROM_RESTORE',
        tabID: 1,
        isRole: false,
        tabName: 'Danh sách Hồ sơ gửi đi',
        sortId: 0,
      },
      {
        roleValue: 128,
        roleName: 'Xuất excel',
        roleIDName: 'FROM_EXPORT',
        tabID: 1,
        isRole: false,
        tabName: 'Danh sách Hồ sơ gửi đi',
        sortId: 0,
      },
      {
        roleValue: 256,
        roleName: 'Tải Hồ sơ',
        roleIDName: 'FROM_DOWNLOAD',
        tabID: 1,
        isRole: false,
        tabName: 'Danh sách Hồ sơ gửi đi',
        sortId: 0,
      },
      {
        roleValue: 512,
        roleName: 'Sao chép địa chỉ trang ký Hồ sơ',
        roleIDName: 'FROM_COPYURL',
        tabID: 1,
        isRole: false,
        tabName: 'Danh sách Hồ sơ gửi đi',
        sortId: 0,
      },
      {
        roleValue: 1024,
        roleName: 'Xem lịch sử Hồ sơ',
        roleIDName: 'FROM_HISTORY',
        tabID: 1,
        isRole: false,
        tabName: 'Danh sách Hồ sơ gửi đi',
        sortId: 0,
      },
    ],
  },
  {
    id: 2,
    name: 'Danh sách Hồ sơ gửi đến',
    numberShow: 0,
    parentId: 0,
    isVisitTab: true,
    isFocusTab: false,
    sortId: 1,
    listRoles: [
      {
        roleValue: 1,
        roleName: 'Truy cập trang',
        roleIDName: 'TO_LIST',
        tabID: 2,
        isRole: false,
        tabName: 'Danh sách Hồ sơ gửi đến',
        sortId: 1,
      },
      {
        roleValue: 2,
        roleName: 'Xem tất cả Hồ sơ của Đơn vị',
        roleIDName: 'TO_ALL',
        tabID: 2,
        isRole: false,
        tabName: 'Danh sách Hồ sơ gửi đến',
        sortId: 1,
      },
      {
        roleValue: 4,
        roleName: 'Xem chi tiết Hồ sơ',
        roleIDName: 'TO_VIEWDETAIL',
        tabID: 2,
        isRole: false,
        tabName: 'Danh sách Hồ sơ gửi đến',
        sortId: 1,
      },
      {
        roleValue: 8,
        roleName: 'Ký Hồ sơ',
        roleIDName: 'TO_APPROVE',
        tabID: 2,
        isRole: false,
        tabName: 'Danh sách Hồ sơ gửi đến',
        sortId: 1,
      },
      {
        roleValue: 16,
        roleName: 'Xuất excel',
        roleIDName: 'TO_EXPORT',
        tabID: 2,
        isRole: false,
        tabName: 'Danh sách Hồ sơ gửi đến',
        sortId: 1,
      },
      {
        roleValue: 32,
        roleName: 'Tải Hồ sơ',
        roleIDName: 'TO_DOWNLOAD',
        tabID: 2,
        isRole: false,
        tabName: 'Danh sách Hồ sơ gửi đến',
        sortId: 1,
      },
    ],
  },
  {
    id: 6,
    name: 'Quản lý Mẫu hồ sơ',
    numberShow: 0,
    parentId: 0,
    isVisitTab: true,
    isFocusTab: false,
    sortId: 3,
    listRoles: [
      {
        roleValue: 1,
        roleName: 'Truy cập trang',
        roleIDName: 'TYPE_LIST',
        tabID: 6,
        isRole: false,
        tabName: 'Quản lý Mẫu hồ sơ',
        sortId: 3,
      },
      {
        roleValue: 2,
        roleName: 'Cấu hình Mẫu hồ sơ',
        roleIDName: 'TYPE_CONFIG',
        tabID: 6,
        isRole: false,
        tabName: 'Quản lý Mẫu hồ sơ',
        sortId: 3,
      },
      {
        roleValue: 4,
        roleName: 'Thêm/Sửa/Xóa Mẫu hồ sơ',
        roleIDName: 'TYPE_ADD_EDIT_DELETE',
        tabID: 6,
        isRole: false,
        tabName: 'Quản lý Mẫu hồ sơ',
        sortId: 3,
      },
    ],
  },
  {
    id: 11,
    name: 'Quản lý Mẫu văn bản',
    numberShow: 0,
    parentId: 0,
    isVisitTab: true,
    isFocusTab: false,
    sortId: 4,
    listRoles: [
      {
        roleValue: 1,
        roleName: 'Truy cập trang',
        roleIDName: 'TEXTSAMPLE_LIST',
        tabID: 11,
        isRole: false,
        tabName: 'Quản lý Mẫu văn bản',
        sortId: 4,
      },
      {
        roleValue: 2,
        roleName: 'Thêm/Sửa/Xóa Mẫu văn bản',
        roleIDName: 'TEXTSAMPLE_ADD_EDIT_DELETE',
        tabID: 11,
        isRole: false,
        tabName: 'Quản lý Mẫu văn bản',
        sortId: 4,
      },
    ],
  },
  {
    id: 10,
    name: 'Quản lý Đối tác',
    numberShow: 0,
    parentId: 0,
    isVisitTab: true,
    isFocusTab: false,
    sortId: 5,
    listRoles: [
      {
        roleValue: 1,
        roleName: 'Truy cập trang',
        roleIDName: 'PARTNER_LIST',
        tabID: 10,
        isRole: false,
        tabName: 'Quản lý Đối tác',
        sortId: 5,
      },
      {
        roleValue: 2,
        roleName: 'Thêm mới',
        roleIDName: 'PARTNER_INSERT',
        tabID: 10,
        isRole: false,
        tabName: 'Quản lý Đối tác',
        sortId: 5,
      },
      {
        roleValue: 4,
        roleName: 'Cập nhật',
        roleIDName: 'PARTNER_UPDATE',
        tabID: 10,
        isRole: false,
        tabName: 'Quản lý Đối tác',
        sortId: 5,
      },
      {
        roleValue: 8,
        roleName: 'Xóa',
        roleIDName: 'PARTNER_DELETE',
        tabID: 10,
        isRole: false,
        tabName: 'Quản lý Đối tác',
        sortId: 5,
      },
    ],
  },
  {
    id: 7,
    name: 'Quản lý Tài khoản',
    numberShow: 0,
    parentId: 0,
    isVisitTab: true,
    isFocusTab: false,
    sortId: 6,
    listRoles: [
      {
        roleValue: 1,
        roleName: 'Truy cập trang',
        roleIDName: 'UNIT_LIST',
        tabID: 7,
        isRole: false,
        tabName: 'Quản lý Tài khoản',
        sortId: 6,
      },
      {
        roleValue: 2,
        roleName: 'Cập nhật thông tin đơn vị',
        roleIDName: 'UNIT_UPDATE',
        tabID: 7,
        isRole: false,
        tabName: 'Quản lý Tài khoản',
        sortId: 6,
      },
      {
        roleValue: 4,
        roleName: 'Thêm mới, Xóa Chữ ký số',
        roleIDName: 'UNIT_ADD_DELETE',
        tabID: 7,
        isRole: false,
        tabName: 'Quản lý Tài khoản',
        sortId: 6,
      },
      {
        roleValue: 8,
        roleName: 'Cấu hình nâng cao',
        roleIDName: 'UNIT_ADV',
        tabID: 7,
        isRole: false,
        tabName: 'Quản lý Tài khoản',
        sortId: 6,
      },
    ],
  },
  {
    id: 4,
    name: 'Quản lý Nhóm quyền',
    numberShow: 0,
    parentId: 0,
    isVisitTab: true,
    isFocusTab: false,
    sortId: 7,
    listRoles: [
      {
        roleValue: 1,
        roleName: 'Truy cập trang',
        roleIDName: 'NQ_MENU',
        tabID: 4,
        isRole: false,
        tabName: 'Quản lý Nhóm quyền',
        sortId: 7,
      },
      {
        roleValue: 2,
        roleName: 'Thêm mới',
        roleIDName: 'NQ_INSERT',
        tabID: 4,
        isRole: false,
        tabName: 'Quản lý Nhóm quyền',
        sortId: 7,
      },
      {
        roleValue: 4,
        roleName: 'Cập nhật',
        roleIDName: 'NQ_UPDATE',
        tabID: 4,
        isRole: false,
        tabName: 'Quản lý Nhóm quyền',
        sortId: 7,
      },
      {
        roleValue: 8,
        roleName: 'Xóa',
        roleIDName: 'NQ_DELETE',
        tabID: 4,
        isRole: false,
        tabName: 'Quản lý Nhóm quyền',
        sortId: 7,
      },
    ],
  },
  {
    id: 5,
    name: 'Quản lý Người dùng',
    numberShow: 0,
    parentId: 0,
    isVisitTab: true,
    isFocusTab: false,
    sortId: 8,
    listRoles: [
      {
        roleValue: 1,
        roleName: 'Truy cập trang',
        roleIDName: 'PQ_MENU',
        tabID: 5,
        isRole: false,
        tabName: 'Quản lý Người dùng',
        sortId: 8,
      },
      {
        roleValue: 2,
        roleName: 'Phân quyền',
        roleIDName: 'PQ_INSERT',
        tabID: 5,
        isRole: false,
        tabName: 'Quản lý Người dùng',
        sortId: 8,
      },
      {
        roleValue: 4,
        roleName: 'Thêm mới, Cập nhật, Xóa',
        roleIDName: 'PQ_CRUD',
        tabID: 5,
        isRole: false,
        tabName: 'Quản lý Người dùng',
        sortId: 8,
      },
      {
        roleValue: 8,
        roleName: 'Đặt lại mật khẩu',
        roleIDName: 'PQ_RESET_PW',
        tabID: 5,
        isRole: false,
        tabName: 'Quản lý Người dùng',
        sortId: 8,
      },
      {
        roleValue: 16,
        roleName: 'Cấu hình nâng cao',
        roleIDName: 'PQ_RESET_ADV',
        tabID: 5,
        isRole: false,
        tabName: 'Quản lý Người dùng',
        sortId: 8,
      },
    ],
  },
  {
    id: 9,
    name: 'Cấu hình Thông báo',
    numberShow: 0,
    parentId: 0,
    isVisitTab: true,
    isFocusTab: false,
    sortId: 9,
    listRoles: [
      {
        roleValue: 1,
        roleName: 'Truy cập trang',
        roleIDName: 'CONFIG_LIST',
        tabID: 9,
        isRole: false,
        tabName: 'Cấu hình Thông báo',
        sortId: 9,
      },
    ],
  },
  {
    id: 8,
    name: 'Tracứu Log',
    numberShow: 0,
    parentId: 0,
    isVisitTab: true,
    isFocusTab: false,
    sortId: 10,
    listRoles: [
      {
        roleValue: 1,
        roleName: 'Truy cập trang',
        roleIDName: 'LOG_LIST',
        tabID: 8,
        isRole: false,
        tabName: 'Tra cứu Log',
        sortId: 10,
      },
    ],
  },
  {
    id: 0,
    name: 'Trang Đăng nhập hệ thống',
    numberShow: 0,
    parentId: 0,
    isVisitTab: false,
    isFocusTab: false,
    sortId: 11,
    listRoles: [],
  },
  {
    id: 12,
    name: 'Quản lý Loại Mẫu văn bản',
    numberShow: 0,
    parentId: 0,
    isVisitTab: false,
    isFocusTab: false,
    sortId: 12,
    listRoles: [],
  },
];
